language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAJVTYYE5DWHGHIA7A
  bucket: sebastianvoss.com
  acl: public_read
  region: eu-central-1
  local_dir: public
  secret_access_key:
    secure: PxnXY3s9WbGLKQVrY5h+jCdSI2MooSiYN0Y2n7LMNdESPaepsEcqzMKX+bA9tXCA8TUlr8VUAeaPzmeRibycMwJU8EmCD9axIKvaBt3xEWo9/WB1VRJOmc7GWd6lYzC0gEjQ8mrzNOKJM5lwJVGIwIx8DtPWv1v5yDlvLZ1dcOupURAZhWXIosVRduCvCd0bA7v0bCobEiavwxxjIXlC6q7GqHmvfFfyGL+fYNXVOOhBCiTzkBuWGLNt6HjVfCseJN9+FSlfzmv2GgZxNbhhJY/HclqHH2q3LCddgmCXbuChS2kFYJ9IHDu/H5F3PcPtskchFqdD/i7DFtGno9nD1gmv7ZIqB9cEakBVIceYDwmDplXf7tHEuoXB2T8vI9195Ns2tJIUHn3Qi1NYK4JqWzAw1swtKskTIMMyP5vZNf+HRsfSjqp/X1VG7Pzx+ws4784Rwsm/38hGgNWRFG4dR1mRabGdXdGUKzCvf5667r7Hy2tOO0pecFWmrFTOA5w55CPVJYaefNzEy4URjvyZpkwk4HR8wMbo3hKgeGpPqSHinCCPF3dFuZi+xqPNCFcpkr1wLIntb+1ARW+/a0yZWw74iEtCG2pYKGd8d4788DCI9f1Ru0QyfucsfiWhVu2NiZxYnI3Q1vtd+vStQC0YIpBQPPe+oc4l1VDWMm+ljAQ=
