language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAJVTYYE5DWHGHIA7A
  bucket: sebastianvoss.com
  acl: public_read
  region: eu-central-1
  secret_access_key:
    secure: mpXUE+riOawbjKiuwsLLfKVG6XQTvzqawV6NRT/3LUaEUEMxCIL5eEgGhOOmTW5xJGhAH9ZGANhfwiS2jpLTTjnF2Ejte5tfaBFFF4RUGMtDSUip50jOareR6xeZatFIdUdXydbvXSS71ZeEMKF2JcOgnUtnStntUN3Bem6q1x4H8F+GhOxB7VJ6S75PHwUOGmlqDiuat9DCQNN3qiFHK1U5K1ZAN5sNbYerpz3UzNevALWYot2ULavsuqgu8FeK86sSBejKQbxArXmaSoS2fwL1woAhcySFS4Ug4Lz8bNl4/4Nt28Ou6oET59cGaanvFNbHKmNOXLQmTjz3UQCYvxguB1FYCDh3JmFT5hSgQ7icpTdeEzj7Hdf5EH7H/TEZo2MRiU14E5AaY76doF1CW6HtG05cRxfZzoiFF976n0rHJxUwC9TknTs2Lf/N3StbX1gvbaLIh/joADJUD8nmAURg0EiS2Xbuaua2+DFSFVdT9Op61O1O6VLJ7Ojwqjut9aM9TVZFk3H6yMj+9sANBM9/7DGcz4JDGtHcXVQBKpCBLXTzHDNCOgE4G7xZedVFJj/iszX8li88yxcPLvRxdttQ6cYxbQsSdEqUCBTbQPgs24PKqaNkSosycoPJYETnlH//3hr2u0cZ04kl48aGBtZlpt76rx0VZAyrkzgik8I=
