language: node_js
node_js:
- node

# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - cd src
  - ../binaries/hugo

deploy:
  provider: s3
  access_key_id: AKIAJVTYYE5DWHGHIA7A
  bucket: sebastianvoss.com
  acl: public_read
  region: eu-central-1
  local_dir: src/public
  skip_cleanup: true
  secret_access_key:
    secure: EuZYwjNyqco2k8BK1QqGNkAVczPc3DPhvT4cq66hO9dtvSXH7RcSIHAPwJGWArgqS4RJCFMZo9MEqsEdj2rYY3ldyXAF3n2qK2MRRznlW4REz98jbEk0UZC2xnlEEaHjhxkKdIbz2SziyvRqnCYut1UD41JIQjmUdTYKqHWQSbIXAj4AZobQ7FnhrJ6rH/Y0Y1plz27EWEjMObSU/MgsjHnPUmZTlhw7w353qI+CGxbQt/2QEJBsYAED7xvIS4YYvpMVCPCqFEjETgT+6I1MEm93BiN+B2AsU99/WSZaSs1O+JTp1caS2TOcvhlzzy3ITg5ym4H6jL/tG4EmPmbqP55O6qrcGKRsVo3pPCYUvTfebH58z/P8ZMIx754m+uHlbfhNoZOjSwZ7JfD763S8s4XxWxNXrxPb0Nz2XiWzju94Onbfv6BaVAYs4u+QbD1lpYCFt5Qi+ORrV8cDJ2vR3qYT/TfhV5Q2liO5M+fGcCpgiXz/jz1OYoK0h3cHjLI7LF6QmAUHDWDiBvHVRgTa8gSBdqlaPBBf+3CtuiLm5h9eqO35XRzvEg9VxGCcHTjutS2BncLZexdDjLJzM3vQIPXXNg2zDQ8LXNMQL+AaQVXkxbDD1cKclQss/lis+5lrMD1FbHwJNKE7gEaWdtwOqYjceAwCRNvynMh3ojTp2bQ=
