theme = "hugo-coder" # set the theme
baseURL = "https://sebastianvoss.com/"

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params] # theme parameters
    author = "Sebastian Voss" # author's name
    info = "Full Stack Software Engineer" # author's job title or info
    description = "Sebastian Voss's personal website" # site description
    keywords = "blog,developer,personal" # site keywords

    # wether you want to hide copyright and credits in the footer
    hideCredits = true
    hideCopyright = false
    
# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/sebastianvoss/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/sebastian_voss/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/sevoss/"

# Menu links
[[menu.main]]
    name = "Home"
    weight = 1
    url  = "/"

[[menu.main]]
    name = "Blog"
    weight = 0
    url  = "/posts/"
